### ISSUE TITLE
Don't block thread in suspending function

### ISSUE THREAD

**Issue by zeldigas** [RichoDemus/autoplaylist#3]
Hello, during searching for kotlin libs with retries I found your project.

The problem I found - you are doing Thread.sleep that is simply block the whole thread and does not make sense for coroutine based code: https://github.com/RichoDemus/autoplaylist/blob/master/autoplaylist-backend/server/spotify-adapter/src/main/kotlin/com/richodemus/autoplaylist/spotify/SpotifyAdapter.kt#L81

Replacing it with delay() would fix the problem. Reference: https://kotlinlang.org/docs/reference/coroutines/basics.html#waiting-for-a-job

**Comment by RichoDemus** [comment]
Hi, thanks for reaching out.
You're completely right, silly mistake of me :)

**Comment by RichoDemus** [comment]
resolved in 6efd68e3b26af80681c6e717cb71edb5517f07e1

thanks for contributing!
